import { ImpactPalette, ImpactPreset } from '../types/impact';

const CYAN_INTERCEPT: ImpactPalette = {
  flash: '#f4fbff',
  glow: '#7feaff',
  ring: '#00e5ff',
  smoke: '#9de6ff',
  streak: '#d9fbff',
  aftermath: '#74e0ff',
};

const HEAVY_INTERCEPT: ImpactPalette = {
  flash: '#fff6eb',
  glow: '#ffc987',
  ring: '#ffd799',
  smoke: '#ffd6ae',
  streak: '#fff2df',
  aftermath: '#ffc46b',
};

const TERMINAL_IMPACT: ImpactPalette = {
  flash: '#fff3eb',
  glow: '#ffb26b',
  ring: '#ff8c4a',
  smoke: '#ffcfab',
  streak: '#ffd7b7',
  aftermath: '#ff944d',
};

const EMP_PULSE: ImpactPalette = {
  flash: '#eaf7ff',
  glow: '#8fd4ff',
  ring: '#88c7ff',
  smoke: '#b9e5ff',
  streak: '#f5fbff',
  aftermath: '#82bfff',
};

export const IMPACT_PRESETS: Record<string, ImpactPreset> = {
  small_intercept: {
    id: 'small_intercept',
    intensity: 'medium',
    durationMs: 2000,
    radiusM: 24_000,
    ringSpeedMps: 28_000,
    smokeLifetimeMs: 3400,
    smokeRiseM: 1800,
    particleCount: 16,
    aftermathLifetimeMs: 10_000,
    streakCount: 8,
    palette: CYAN_INTERCEPT,
    flash: { enabled: true, durationMs: 280, maxScale: 1.4, maxOpacity: 0.96 },
    glow: { enabled: true, durationMs: 1200, maxScale: 2.1, maxOpacity: 0.72 },
    ring: { enabled: true, durationMs: 1500, maxScale: 1, maxOpacity: 0.6 },
    smoke: { enabled: true, durationMs: 3400, maxScale: 1.8, maxOpacity: 0.42 },
    streaks: { enabled: true, durationMs: 900, maxScale: 1.2, maxOpacity: 0.7 },
    aftermath: { enabled: true, durationMs: 10_000, maxScale: 1, maxOpacity: 0.34 },
    lod: {
      nearDistanceM: 180_000,
      midDistanceM: 700_000,
      farDistanceM: 2_500_000,
      nearParticleFactor: 1,
      midParticleFactor: 0.5,
      farParticleFactor: 0.2,
    },
    cameraShakeHint: 0.12,
  },
  heavy_intercept: {
    id: 'heavy_intercept',
    intensity: 'high',
    durationMs: 2600,
    radiusM: 42_000,
    ringSpeedMps: 36_000,
    smokeLifetimeMs: 4200,
    smokeRiseM: 2600,
    particleCount: 24,
    aftermathLifetimeMs: 13_000,
    streakCount: 12,
    palette: HEAVY_INTERCEPT,
    flash: { enabled: true, durationMs: 340, maxScale: 1.7, maxOpacity: 1 },
    glow: { enabled: true, durationMs: 1500, maxScale: 2.6, maxOpacity: 0.8 },
    ring: { enabled: true, durationMs: 1750, maxScale: 1, maxOpacity: 0.68 },
    smoke: { enabled: true, durationMs: 4200, maxScale: 2.2, maxOpacity: 0.46 },
    streaks: { enabled: true, durationMs: 1100, maxScale: 1.45, maxOpacity: 0.8 },
    aftermath: { enabled: true, durationMs: 13_000, maxScale: 1, maxOpacity: 0.38 },
    lod: {
      nearDistanceM: 220_000,
      midDistanceM: 900_000,
      farDistanceM: 3_000_000,
      nearParticleFactor: 1,
      midParticleFactor: 0.58,
      farParticleFactor: 0.25,
    },
    cameraShakeHint: 0.16,
  },
  terminal_impact: {
    id: 'terminal_impact',
    intensity: 'high',
    durationMs: 3200,
    radiusM: 58_000,
    ringSpeedMps: 24_000,
    smokeLifetimeMs: 5200,
    smokeRiseM: 4200,
    particleCount: 26,
    aftermathLifetimeMs: 18_000,
    streakCount: 10,
    palette: TERMINAL_IMPACT,
    flash: { enabled: true, durationMs: 420, maxScale: 1.9, maxOpacity: 1 },
    glow: { enabled: true, durationMs: 1800, maxScale: 2.9, maxOpacity: 0.86 },
    ring: { enabled: true, durationMs: 2200, maxScale: 1, maxOpacity: 0.72 },
    smoke: { enabled: true, durationMs: 5200, maxScale: 2.6, maxOpacity: 0.5 },
    streaks: { enabled: true, durationMs: 1200, maxScale: 1.3, maxOpacity: 0.64 },
    aftermath: { enabled: true, durationMs: 18_000, maxScale: 1, maxOpacity: 0.44 },
    lod: {
      nearDistanceM: 240_000,
      midDistanceM: 1_000_000,
      farDistanceM: 3_600_000,
      nearParticleFactor: 1,
      midParticleFactor: 0.62,
      farParticleFactor: 0.28,
    },
    cameraShakeHint: 0.18,
  },
  emp_style_pulse: {
    id: 'emp_style_pulse',
    intensity: 'low',
    durationMs: 1800,
    radiusM: 30_000,
    ringSpeedMps: 40_000,
    smokeLifetimeMs: 2200,
    smokeRiseM: 900,
    particleCount: 10,
    aftermathLifetimeMs: 9000,
    streakCount: 4,
    palette: EMP_PULSE,
    flash: { enabled: true, durationMs: 240, maxScale: 1.3, maxOpacity: 0.92 },
    glow: { enabled: true, durationMs: 900, maxScale: 2, maxOpacity: 0.62 },
    ring: { enabled: true, durationMs: 1200, maxScale: 1, maxOpacity: 0.56 },
    smoke: { enabled: false, durationMs: 0, maxScale: 0, maxOpacity: 0 },
    streaks: { enabled: false, durationMs: 0, maxScale: 0, maxOpacity: 0 },
    aftermath: { enabled: true, durationMs: 9000, maxScale: 1, maxOpacity: 0.28 },
    lod: {
      nearDistanceM: 220_000,
      midDistanceM: 800_000,
      farDistanceM: 2_600_000,
      nearParticleFactor: 1,
      midParticleFactor: 0.4,
      farParticleFactor: 0.15,
    },
    cameraShakeHint: 0.08,
  },
};

export function getImpactPreset(id: string): ImpactPreset {
  return IMPACT_PRESETS[id] ?? IMPACT_PRESETS.small_intercept;
}
